#!/bin/sh

set -e

if [ "$1" = purge ]
then
    rm -rf /etc/console
fi

# Automatically added by dh_installdeb/12.1.1
dpkg-maintscript-helper rm_conffile /etc/init.d/keymap.sh 0.7.88\+nmu1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installdebconf/12.1.1
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

