#!/bin/sh
set -e

# Automatically added by installdeb-ispell/UNDECLARED
dico_class="ispell"
dico_compat="american.compat"

[ -d "/var/lib/$dico_class" ] || mkdir -p "/var/lib/$dico_class"

for i in $dico_compat; do
    >"/var/lib/$dico_class/$i"
done
# End automatically added section


# work-around for #781068
if dpkg --compare-versions "$2" lt-nl "3.4.00-2~"; then
  prefix="/var/lib/ispell/american"
  rm -f "${prefix}.compat" "${prefix}.remove" "${prefix}.hash"
fi
exit 0
