#!/bin/sh
set -e
# Automatically added by dh_installsystemd/12
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'polkit.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/12
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.PolicyKit1.conf 0.105-22\~ -- "$@"
# End automatically added section
